	update-alternatives --install /sbin/e2fsck e2fsck e2fsck.e2fsprogs 100
	update-alternatives --install /sbin/fsck.ext2 fsck.ext2 fsck.ext2.e2fsprogs 100
	update-alternatives --install /sbin/fsck.ext3 fsck.ext3 fsck.ext3.e2fsprogs 100
	update-alternatives --install /sbin/fsck.ext4 fsck.ext4 fsck.ext4.e2fsprogs 100
	update-alternatives --install /sbin/fsck.ext4dev fsck.ext4dev fsck.ext4dev.e2fsprogs 100
