	update-alternatives --install /sbin/mke2fs mke2fs mke2fs.e2fsprogs 100
	update-alternatives --install /sbin/mkfs.ext2 mkfs.ext2 mkfs.ext2.e2fsprogs 100
	update-alternatives --install /sbin/mkfs.ext3 mkfs.ext3 mkfs.ext3.e2fsprogs 100
	update-alternatives --install /sbin/mkfs.ext4 mkfs.ext4 mkfs.ext4.e2fsprogs 100
	update-alternatives --install /sbin/mkfs.ext4dev mkfs.ext4dev mkfs.ext4dev.e2fsprogs 100
