.bd B 3
.TH hex6x 1 "Mar 24, 2010" "TI Tools" "TI Code Generation Tools"
.SH NAME
hex6x - Hex Converter
.SH SYNOPSIS
.B hex6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The hex converter converts an object file into one of several standard hexadecimal formats.
.SH OPTIONS
The following options are accepted by this tool:
.SS General Options:
.SS
.TP
-a
Output ASCII hex format
.TP
-boot
Select boot mode
.TP
-bootorg=addr
Specify origin address or symbol of boot table ROM
.TP
-bootsection=section
Specify boot mode section and placement value
.TP
-byte
Output as bytes rather than target addressing
.TP
-e=addr
Specify entrypoint address or symbol name
.TP
-exclude=section
Exclude section from hex conversion
.TP
-fill=val
Specify fill value
.TP
-h
Display a help message that includes usage and option information [Same as -options]
.TP
-i
Output Intel hex format
.TP
-image
Select image mode
.TP
-linkerfill
Include linker fill sections in images
.TP
-map=file
Specify map file name
.TP
-memwidth=width
Specify memory width
.TP
-m[=1,2,3]
Output Motorola S hex format
.TP
-o=file
Specify output file names
.TP
-olength=num
Number of data items per line of hex output
.TP
-options
Display a help message that includes usage and option information [Same as -h]
.TP
-order=L,M
Specify data ordering (endianness)
.TP
-q
Quiet Operation [Same as -quiet]
.TP
-quiet
Quiet Operation [Same as -q]
.TP
-romwidth=width
Specify rom width
.TP
-t
Output TI-Tagged hex format
.TP
--ti_txt
Output TI-TXT hex format
.TP
-x
Output Extended Tektronix hex format
.TP
-z
Zero based addressing [Same as -zero]
.TP
-zero
Zero based addressing [Same as -z]
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2010, Texas Instruments, Inc.
